Rename to share_poverty_exposure and share_poverty_exposure_quality
UI-Research/mobility-from-poverty pull request #254
Opened 2023-12-21 21:18 UTC by malcalakovalski

Completes issue #207

2024-01-02 16:12 UTC, wcurrangroome requested changes
Whoops--updating the status of this review to "Request changes" rather than "Comment".

2024-03-05 19:20 UTC, awunderground commented on 06_neighborhoods/poverty-exposure/poverty-exposure-city-2021.qmd
> +    share_poverty_exposure_white_nonhispanic_quality = set_quality(cv = poverty_white_nonhispanic_cv, exposure = poverty_exposure_white_nonhispanic)
Good catch. Updated.

2024-03-07 16:46 UTC, wcurrangroome requested changes
No changes needed.

2024-03-07 17:01 UTC, wcurrangroome approved these changes
This is good to merge.

2024-03-07 17:15 UTC, merged