Iss208
UI-Research/mobility-from-poverty pull request #255
Opened 2023-12-21 21:25 UTC by malcalakovalski

Resolves #208. 

Apologies for the messy commit history: I accidentally pushed changes meant for #207 to this branch and had to undo this.

2024-01-02 16:10 UTC, wcurrangroome requested changes
Changes in this PR all look good, but need to check the interpolation (and validation thereof), particularly for Louisville / Jefferson County Metro Government.

2024-01-02 16:10 UTC, wcurrangroome commented on 06_neighborhoods/race-ethnicity-exposure/race-ethnicity-exposure-city-2021.qmd
The below corresponds to an issue that predates this PR:
I only checked the interpolation quickly in this (2021 city) script, not in the other two scripts contained in this PR, but Houston does not appear to be an outlier in terms of the differences between reported and interpolated values; rather, Louisville/Jefferson County Metro Government (balance) appears to be the only place that is substantially off (difference in population is ~250K). From a quick look, it seems like the crosswalk may underreport the number of tracts that intersect with the place boundaries.

It may be helpful to rework the validation visuals when checking the alignment between reported and interpolated values so that it's clearer what is being highlighted (e.g., Houston is automatically highlighted, but the legend is "TRUE" and "FALSE" rather than "HOUSTON" and "OTHER PLACES". Conditionally highlighting and labeling places with a certain magnitude of difference (standardized by the reported value?) between interpolated and reported values--perhaps via a boxplot rather than a scatter grid--and adding a `stopifnot` validation check that incorporates a threshold value for discrepancies between interpolated and reported values might be helpful as well.

2024-03-01 18:29 UTC, awunderground commented on 06_neighborhoods/race-ethnicity-exposure/race-ethnicity-exposure-2018.Rmd
> +    black_nh_exp = share_black_nh_exposure,
I think this is so all of the values are easy to see in the reactable table!

2024-03-01 18:29 UTC, awunderground commented on 06_neighborhoods/race-ethnicity-exposure/race-ethnicity-exposure-2021.Rmd
> +    black_nh_exp = share_black_nh_exposure,
I think this is so all of the values are easy to see in the reactable table!

2024-03-01 18:29 UTC, awunderground commented on 06_neighborhoods/race-ethnicity-exposure/race-ethnicity-exposure-city-2021.qmd
> +    black_nh_exp = share_black_nh_exposure,
I think this is so all of the values are easy to see in the reactable table!

2024-03-01 19:19 UTC, awunderground commented on 06_neighborhoods/race-ethnicity-exposure/race-ethnicity-exposure-city-2021.qmd
This is a great note. I added two tables to evaluate the mismatch and dropped any mention to Houston. 

I think the issue in Louisville has to do with unincorporated places: https://en.wikipedia.org/wiki/Louisville/Jefferson_County_metro_government_(balance),_Kentucky

2024-03-05 02:14 UTC, awunderground commented on 06_neighborhoods/race-ethnicity-exposure/race-ethnicity-exposure-city-2021.qmd
GeoCorr excludes unincorporated places in Louisville. Our places population file does not. Our places population file is even goofier. 

I don't think it matters for this metric since it is just for a check but I will look into it elsewhere. 

<img width="1053" alt="Screen Shot 2024-03-04 at 8 57 16 PM" src="https://github.com/UI-Research/mobility-from-poverty/assets/11818850/521bcb70-9ff3-4024-b224-9d106f75a962">

2024-03-12 20:40 UTC, wcurrangroome approved these changes

2024-03-12 21:35 UTC, merged