Add number of membership associations per 10,000 people
UI-Research/mobility-from-poverty pull request #268
Opened 2024-01-31 01:19 UTC by malcalakovalski

Closes #221

2024-02-27 17:33 UTC, rogin123 commented on 06_neighborhoods/social-capital/social_associations_county.qmd
> +title: "Number of membership associations per 10,000 people — County"
This file looks good!

2024-02-27 18:08 UTC, rogin123 requested changes
I think you should be using a 2020 ZCTA -> 2021 census place crosswalk here instead of 2010. You're downloading 2020 and 2021 data from the census api which should be in 2020 vintage geographies. I think the mismatch is causing 1,786 cbp rows to be dropped when you merge it with the crosswalk

2024-03-01 20:55 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +  # 28,599 observations to 16,644 observations
Yes, it was an old comment. I just updated it and added `tidylog` to make it easier to track changes in number of observations

2024-03-01 20:56 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +
Ah, great catch, thank you! I updated this comment accordingly.

2024-03-13 21:22 UTC, rogin123 approved these changes
Looks good!

2024-03-13 22:59 UTC, tinatinc commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +
Hi, yes! I believe this was intentional -- we don't always have 3 buckets for quality if it's not needed/does not make sense for the data source

2024-03-14 11:51 UTC, awunderground commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +
The original data quality flag was overly generous. The 10% rule was a very low bar. 

I believe @malcalakovalski adopted a process that uses `afact` and `afact2` that aligns with the ACS microdata metrics.

2024-03-14 11:51 UTC, merged