Iss202 past years
UI-Research/mobility-from-poverty pull request #321
Opened 2024-04-04 15:38 UTC by rogin123

Update IPUMS data pull script to include data from 2022 and 2021 for places, and 2022, 2021, 2018, and 2014 for counties

2024-04-04 19:56 UTC, jwalsh28 requested changes
Looks good overall Amy, I found no errors but I think this can be simplified a bit. 

The crosswalk function seems to overcomplicate things a bit, I made a suggestion for simplificaiton in the code. The idea would be adding a crosswalk_period variable to the ACS dataset and including it in the join so you only join once. This would require changes as more years are brought into the crosswalk but we can note that for future users. Up to you though, if you prefer the function that is fine.

2024-04-04 19:56 UTC, jwalsh28 commented on 02_housing/0_housing_microdata.qmd
> +# NOTE TO JP: 2021 is missing data for place fips 72122 in Georgia
Thanks for pointing this out, turns out that city in Georgia was incorporated in 2016 and the pre-2022 crosswalk uses places from 2014 so it's not being captured. Given the limitaitons from GeoCorr I don't think we can manually add it back in.

2024-04-04 19:56 UTC, jwalsh28 commented on 02_housing/0_housing_microdata.qmd
> +map(place_years, prepare_place_data)
I think this function may over complicate the process. Could you just add a variable to the ACS extract also called crosswalk_period where you make the variable pre-2022 and 2022 based on the ACS years and then add is as an argument in the left_join with the crosswalk? This way you don't have to iterate the process, the join happens once for all the data.

2024-04-11 14:29 UTC, rpitingolo commented
@rogin123 is this ready for review? Or is there any more code edits still to push?

2024-04-18 14:03 UTC, rpitingolo commented
@cdsolari I pushed the place data CSVs for 2022 and 2021 and the county CSVs for 2022, 2021, 2018 and 2014.

@jwalsh28 @rogin123 I updated the 2a and 2b QMDs to use a `target_year` object. Ideally I'd want to use functions but in the interest of time this was the faster option.

2024-04-18 15:16 UTC, cdsolari commented on 02_housing/data/available_2021_subgroups_city.csv
we have two cases where the share_affordable_available_30/50/80_ami (aka, for all 3 vars) is NA, but the data quality is 1. It should be NA (see state=23 & county=011; state=35 & county=061.

2024-04-18 15:17 UTC, cdsolari commented on 02_housing/data/available_2021_subgroups_county.csv
we have two cases where the share_affordable_available_30/50/80_ami (aka, for all 3 vars) is NA, but the data quality is 1. It should be NA (see state=23 & county=011; state=35 & county=061.

2024-04-18 15:17 UTC, cdsolari commented on 02_housing/data/available_2022_city.csv
state=06 & place=72016 has NA for all the values, but the quality=1 and it should be NA. Otherwise, looks great!

2024-04-18 15:40 UTC, cdsolari commented on 02_housing/data/housing_city.csv
where the value is NA (for all 3 vars), but quality is not and should be NA: year=2022 state=06 and place=72016 has NA for all the values but the quality=1. The rest looks good!

2024-04-18 15:40 UTC, cdsolari commented on 02_housing/data/housing_county.csv
two cases where the value is NA (for all 3 vars), but quality is not and should be: year=2021 & state=23 & county=011; year=2021 & state=35 & county=061. This is the same for the subgroups file.

2024-04-18 15:40 UTC, cdsolari commented on 02_housing/data/housing_subgroups_county.csv
two cases where the value is NA (for all 3 vars), but quality is not and should be: year=2021 & state=23 & county=011; year=2021 & state=35 & county=061.

2024-04-18 15:41 UTC, cdsolari commented on 02_housing/data/housing_subgroups_city.csv
where the value is NA (for all 3 vars), but quality is not and should be NA:year=2022 state=06 and place=72016 has NA for all the values but the quality=1. The rest looks great.

2024-04-18 15:42 UTC, cdsolari requested changes
The available_2018_county.csv & available_2018_subgroups_county.csv look good! 

The avaialble_2014_county looks good. 

For available_2021_county, we have two cases where the share_affordable_available_30/50/80_ami (aka, for all 3 vars) is NA, but the data quality is 1. It should be NA (see state=23 & county=011; state=35 & county=061. This also extends to the subgroup file for available_2021_subroups_county. 
 
Available_2021_city.csv - looks good
 
Available_2021_subgroups_city.csv - looks good
 
Avaialble_2022_city.csv - state=06 & place=72016 has NA for all the values, but the quality=1 and it should be NA. 
 
Also, is it ok that available 2022_subgroups_city wasn't updated?
 
Housing_city - where the value is NA (for all 3 vars), but quality is not and should be NA:year=2022 state=06 and place=72016 has NA for all the values but the quality=1
This is the same issue for the subgroups file
 
Housing_county - two cases where the value is NA (for all 3 vars), but quality is not: year=2021 & state=23 & county=011; year=2021 & state=35 & county=061. This is the same for the subgroups file.

2024-04-18 18:04 UTC, cdsolari approved these changes
Those few changes are clearly made for the 2022 city and city subgroups files for affordable & available

2024-04-18 18:06 UTC, rpitingolo commented
Don't merge it yet! I still have to push the county files.

2024-04-18 19:44 UTC, rpitingolo commented
@cdsolari remaining CSVs and code are pushed

2024-04-18 20:16 UTC, cdsolari approved these changes
All the issues with a metric value that was NA but the quality was not are fixed for all the files that were identified with the issue. It all looks solid. Note that I didn't review the code, but I did review the output and it all looks as I'd expect and to our standards.

2024-04-18 20:51 UTC, merged