Iss328
UI-Research/mobility-from-poverty pull request #329
Opened 2024-04-15 16:23 UTC by awunderground

2024-04-16 13:04 UTC, jwalsh28 requested changes

2024-04-16 13:04 UTC, jwalsh28 commented on geographic-crosswalks/data/county-populations.csv
This version still has the low number of counties for 2021

2024-04-16 16:46 UTC, awunderground commented on 10_construct-database/61_construct_place_all.qmd
> +
I just added everything else. I'm waiting on housing.

2024-04-16 16:47 UTC, awunderground commented on geographic-crosswalks/data/county-populations.csv
I think I fixed that now!

2024-04-16 16:48 UTC, jwalsh28 commented on 10_construct-database/11_construct_county_all.qmd
> +
I forgot this starts by joining onto the population file which has 2023 information, this is fine

2024-04-17 13:24 UTC, jwalsh28 approved these changes
These look ready to rock

2024-04-17 13:27 UTC, merged