Fix naming issues with combine files
UI-Research/mobility-from-poverty pull request #343
Opened 2024-04-24 15:26 UTC by jwalsh28

2024-04-24 15:51 UTC, cdsolari commented on 10_construct-database/61_construct_place_all.qmd
Can you change the "asian_other" to share_desc_rep_other, share_desc_rep_other_quality in all your files? This is what we told Graphicacy to expect. If you feel strongly about it, we can communicate this change and it shouldn't be too late!

2024-04-24 15:53 UTC, cdsolari requested changes
We still have places in several files where the "asian_other" isn't changed to share_desc_rep_other, share_desc_rep_other_quality. Is that something we can change? I also know that Aaron made a last minute decision to change all the racial sub-area labels to something like white communities, communities of color, and mixed communities. Can we chat about this? It is lowest priority though!

2024-04-25 17:54 UTC, cdsolari approved these changes
Looks like all the intended changes worked!

2024-04-25 18:02 UTC, jwalsh28 commented
Great! Leaving this PR open for now just in case we stumble across anyhting else as we are finalizing tests.

2024-04-26 18:32 UTC, merged