Initial PR for preschool update, adding historical years
UI-Research/mobility-from-poverty pull request #429
Opened 2024-11-08 15:06 UTC by jwalsh28

2024-12-19 04:16 UTC, jwalsh28 commented
@ridhi96 See my last commit. I'm having trouble with making aws.s3 compatible with IPUMSR. Let's chat about potential solutions.

2025-02-19 23:43 UTC, ridhi96 requested changes
Hi @jwalsh28! I have reviewed and added my feedback comments. Please let me know if you have any questions on this, thank you!

Also, I am not quite sure what to do about the HTML files.

2025-02-19 23:43 UTC, ridhi96 commented on 08_education/preschool_county_calculate.qmd
> +* **Vacancy:** reported as "0". Note there should be no vacancy results by default of the structure of census data read in (all should be "0"). Confirm this is true with the following test.
Might be useful to add link to variable description.

2025-02-19 23:43 UTC, ridhi96 commented on 08_education/preschool_place_calculate.qmd
>  ### Write out intermediate data
In line 539, it is mentioned that `grade_attending` should never be NA but the graph does show `N/A` string value counts. Please rephrase/add some clarity here as this statement can be a little confusing.

2025-02-19 23:43 UTC, ridhi96 commented on 08_education/preschool_place_calculate.qmd
In a lot of places in this code file `counties` are mentioned (e.g. line 557, 587 etc.) when it should be `places`. Please check and update.

2025-02-19 23:43 UTC, ridhi96 commented on 08_education/preschool_place_calculate.qmd
>  ```{r}
Briefly explain what the functions `calc_survey_mean`, `calc_survey_mean_subgroup` and `finalize_metric` do (wherever they are mentioned).

2025-02-19 23:43 UTC, ridhi96 commented on 08_education/preschool_place_calculate.qmd
>  ### Read intermediate files
I think it would be helpful to explain here why some files are stored in AWS and how that relates to the process for validation.

2025-02-19 23:43 UTC, ridhi96 commented on 08_education/preschool_place_calculate.qmd
>  Function reads the CSVs from intermediate folder or from AWS if the user has access.
Need to add final evaluation function before export.

2025-02-19 23:43 UTC, ridhi96 commented on 08_education/run_preschool_years.qmd
I think it would be useful to explain at the top what the intent of this file and why we are generating place data like this.

2025-02-27 00:52 UTC, jwalsh28 commented on 08_education/preschool_county_calculate.qmd
> +count(acs, sample)
Yes, I think this is actaully very important with the AWS storage system because it's one of the only checks to confirm we have the right year of IPUMS data. I updated the note to make this more clear.

2025-02-27 00:57 UTC, jwalsh28 commented on 08_education/preschool_county_calculate.qmd
> +length(unique(pull(repwts_person, unique_person_id)))
The `ipums_repwt_pre_k_aws` filters the age of respondents directly during the IPUMS API call. I added a note on this above the chunk where the function is used.

2025-02-27 01:00 UTC, jwalsh28 commented on 08_education/preschool_county_calculate.qmd
> +Look at the distribution of ACS survey samples in the data. The number of different samples should align with the number of surveys selected in the extract ipums function.
Updated

2025-02-27 01:12 UTC, jwalsh28 commented on 08_education/preschool_place_calculate.qmd
>  # DO NOT PUSH YOUR API KEY. You only have to run this once and then comment it out as below.
Same note as above

2025-02-28 00:13 UTC, ridhi96 requested changes
Hi @jwalsh28, just left some minor comments that shouldn't take long to fix. The code looks good, thank you!

2025-02-28 00:13 UTC, ridhi96 commented on 08_education/run_preschool_years.qmd
> +Select which years of new data you want to run the preschool place calculate file for.
I think this file generates county files too. Please add a short explanation of the purpose of this file so any future metric leads can figure out if they need to update this. Thanks!

2025-02-28 23:15 UTC, ridhi96 requested changes
Hi @jwalsh28! Thank you for updating the reviewed files. When you changed the year to "2023", the graphs showing the `prek_attendance` metric in `preschool_place.qmd` and `preschool_county.qmd` files need to be updated to display the year "2023" as they still show "2021".

2025-03-03 19:06 UTC, jwalsh28 commented
@ridhi96 I updated the graphics in the validity section to use the year in the Params argument, given how the program is set up this should always reflect the latest year.

2025-03-10 15:34 UTC, ridhi96 approved these changes

2025-03-17 17:13 UTC, jwalsh28 commented
Closes #399

2025-03-17 17:13 UTC, merged