Initial PR submission for the descriptive representation update. Back…
UI-Research/mobility-from-poverty pull request #432
Opened 2024-12-03 20:32 UTC by jwalsh28

…-updated for years 2014, 2016 and 2018. Updated program to run more efficiently and calculate all years at once. Still waiting on 2023 5-year release.

2025-02-14 22:13 UTC, ridhi96 requested changes
Hi @jwalsh28! Added some very minor comments and flagged the need to update the final evaluation function/forms. The code is in good shape!

2025-02-14 22:13 UTC, ridhi96 commented on 05_local-governance/descriptive-representation/descriptive_representation_denom.qmd
>  Construct asian_other (combined value).
Might be good to add more detail apart from the code to show what `asian_other` represents.

2025-02-14 22:13 UTC, ridhi96 commented on 05_local-governance/descriptive-representation/descriptive_representation_denom.qmd
> +Visualize a distribution of county and place population shares for each race/ethnicity group to look for any surprising patterns in the most recent years.
It would be helpful to mention the year being depicted in the plots.

2025-02-14 22:13 UTC, ridhi96 commented on 05_local-governance/descriptive-representation/descriptive_representation_denom.qmd
>  Test to see if bounded by 0 and 1.
Adding a test to verify that the required counties/places for each year are present in the final data might be helpful (just to show we have the expected number of rows/geographies for each year).

2025-02-14 22:13 UTC, ridhi96 commented on 05_local-governance/descriptive-representation/descriptive_representation_denom.qmd
>  ## Export
The code needs to go through the final data evaluation function and the evaluation forms need to be moved to the right folder.

2025-02-27 22:29 UTC, ridhi96 requested changes
Hi @jwalsh28, great work on streamlining the code! I have a review comment on the number of places that show up for `2014` in the data. I think it needs to be evaluated as that impacts the outputs.

And you'd have to delete the evaluation forms from the `data/final` folder and push that in the next commit so we don't accidentally retain them in the wrong folder. Thank you!

2025-02-27 22:29 UTC, ridhi96 commented on 05_local-governance/descriptive-representation/descriptive_representation_denom.qmd
> +wide_places_demo %>%
Number of places for 2014 show up as `970` which is not right, I think a previous step is doubling the count when we add places from `2015` data for `2014`

2025-02-28 19:47 UTC, jwalsh28 commented on 05_local-governance/descriptive-representation/descriptive_representation_denom.qmd
> +Place population file does not have 2014 so we will create a duplicate of 2015 data, change the year to 2014 and recombine the file. The population data from the county geography file is not used but
Great catch, I forgot we had updated the place population file to include 2014 so this step become obsolete and was causing the code to duplicate 2014. I removed the chunk entirely.

2025-02-28 22:29 UTC, ridhi96 approved these changes

2025-03-17 17:58 UTC, merged