Initial updates for 2016 with questions (added as comments in the markdown file)
UI-Research/mobility-from-poverty pull request #433
Opened 2024-12-05 08:34 UTC by ridhi96

In the 2020 update, NJ and KY were flagged as having data quality issues. I am unsure how to interpret the VEST data and figure out which states for 2016 don't have reliable data. I have more concerns around the total votes from the presidential election calculated with the VEST data vs the total votes reported on Wikipedia.

2025-01-23 16:43 UTC, jwalsh28 approved these changes
@ridhi96 Overall I think this update is mostly there. A few major items:

1. I put a recommendation for the quality issue (allocation). For 2016 I don't believe there were any major allocation issues like there were in 2020 due to COVID. Double-check this. My suggestion is to set all allocation quality to 1.
2. MIT vs VEST comparison - there is a comment from the 2020 code that suggests flagging counties in the top quartile of difference from the MIT counts. If time permits I think this would be a good addition to our quality method but you would have to make the update to both years.
3. Make sure when you read this file out you update the years to 2016 and please run the evalution function.

2025-01-23 16:43 UTC, jwalsh28 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +# QUESTION (Ridhi): Should I remove this section?
Yes I think this is fine to delete

2025-01-23 16:43 UTC, jwalsh28 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +  download.file(
I'm having trouble with the way R is downloading this file. The CSV that results from this download leads to a fatal error tha makes R abort when I use `read_csv`. Not sure if this is just an issue with my version of R

2025-01-23 16:43 UTC, jwalsh28 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +QUESTION (Ridhi): There were a lot of precincts/counties where votes were apportioned using weights, boundary conflicts etc. I am not sure how to take this into account for quality here. Below text i
I looked around at the information VEST provides online and found nothing about significant interpolation happening in 2016 the way they did for the 2020 data due to COVID. Maybe double-check VEST resources to see if you can find anything but I think allocation_quality in 2016 data would all be 1.

2025-01-23 16:43 UTC, jwalsh28 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +    # QUESTION (Ridhi): DO I NEED AN IDENTIFYING COLUMN FOR EACH STATE FILE?
I don't think you do, it looks like the identifying columns are appended later in the code using spaital joins.

2025-01-23 16:43 UTC, jwalsh28 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +# # XX Maybe identify counties in the top quartile of percentage difference and flag each place in those counties for quality? Will be annoying because places cross county lines
This would be one major area for improvement if you have time. I believe the idea here is to compare MIT count-level votes with VEST aggregates and take the top quartile (though play around with what makes sense) of difference in terms of counts. Then identifying which places are in those counties and give them a 3 for quality. This would be an addition to our quality method. Again, I don't think this is crucial but if you have the time  it could be a nice change.

2025-01-23 16:43 UTC, jwalsh28 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +  # QUESTION (Ridhi): What is the purpose of `total_precinct_meters` when area is already in meters squared unit?
It looks like this step converts the area calculation into square feet (international foot definition (i.e., 1 foot = 0.3048 meter exactly)). I'm not sure what the purpose is but maybe update that variable name to reflect feet instead of meters.

2025-02-13 00:19 UTC, ridhi96 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +### TO DELETE
Done

2025-02-13 00:20 UTC, ridhi96 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +# QUESTION (Ridhi): The difference in votes is concerning
Added this info.

2025-02-13 00:20 UTC, ridhi96 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +# QUESTION (Ridhi): Should I remove this section?
I have removed the entire section testing for MIT.

2025-02-13 00:23 UTC, ridhi96 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +  download.file(
Please recheck this! I made some update to this section and the download works for me.

2025-02-13 00:25 UTC, ridhi96 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +QUESTION (Ridhi): There were a lot of precincts/counties where votes were apportioned using weights, boundary conflicts etc. I am not sure how to take this into account for quality here. Below text i
I didn't find anything like the interpolation in 2020 although some states like Texas had a lot interpolation based on other factors like change in precinct or other boundaries, reporting of votes for combined geographies etc. I have assigned a quality of 1 to all states for now. More information on data collection is [here](https://dataverse.harvard.edu/file.xhtml?fileId=10596694&version=94.0).

2025-02-13 00:40 UTC, ridhi96 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +  # QUESTION (Ridhi): What is the purpose of `total_precinct_meters` when area is already in meters squared unit?
Yeah I double-checked that according to the calculation it is converting meters squared into feet squared. I am a little confused as to why this was done because there is a calculation for the area of the US that precincts cover. In the 2020 code, the feet squared number is taken into account for this calculation. When I do a similar calculation I get 2924296049648 / 9328197826286 = 0.313 which is 31.3% and is close to the estimate of 31.46% from the 2020 file. But I think this is wrong as we are dividing what appears to be two different units i.e. feet and meters. But if I take the original area in meters from my data, 9594127956221 / 9328197826286 = 1.02 which is 102%. This also doesn't make sense. I am not sure what to do with this.

2025-02-13 00:52 UTC, ridhi96 commented
Hi @jwalsh28, I updated the metric based on your review comments. Please take a look at my responses to your comments when you review again. Thank you!

2025-02-21 16:44 UTC, jwalsh28 approved these changes
Changes look good!

2025-02-21 16:44 UTC, jwalsh28 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +  download.file(
Still getting a fatal error from this that shuts down my R. If it works for you though I think this is probably fine and just a wierd issue with my R version.

2025-02-21 16:49 UTC, jwalsh28 commented on 05_local-governance/voter-turnout/voter-turnout-city-2016.Rmd
> +  # QUESTION (Ridhi): What is the purpose of `total_precinct_meters` when area is already in meters squared unit?
Given this is just a test I am not too worried about it. As a note for future reviewers, it is unclear what this test is showing.

2025-02-21 16:53 UTC, jwalsh28 requested changes
@ridhi96 Sorry I approved prematurely. To finalize this update can you render `voter-turnout-city-2016.Rmd` so that we have an HTML version and make sure to read out the updated final data.

2025-03-05 16:52 UTC, jwalsh28 commented
We confirmed with another reviewer that the issue I was having with my R session aborting is likely specific to my software - this is good to go!

2025-03-05 16:53 UTC, jwalsh28 approved these changes
Confirmed with another reviewer that the program runs without causing R to abort - good to go!

2025-03-17 17:57 UTC, merged