Iss435
UI-Research/mobility-from-poverty pull request #437
Opened 2024-12-17 21:33 UTC by ekgutierrez1

The city homeless student files for 2019-2022 are ready. Specifically the total homeless student file and the subgroup by race file. I'll now turn to the county versions of the same.

2024-12-18 21:15 UTC, ekgutierrez1 commented
The county homeless student files for 2019-2022 are ready. Specifically the total homeless student file and the subgroup by race file. One big flag: CT counties prior to 2022 are not in crosswalk and therefore not in this data. This will need to be rerun when the crosswalk is fixed.

2025-01-09 17:49 UTC, ekgutierrez1 commented
CT is now available for prior years based on the updated crosswalk for all homelessness 2019-2022 as well as subgroups 2019-2022

2025-01-09 19:06 UTC, rpitingolo commented
@ekgutierrez1 just finished reviewing. I will have line item comments in a bit. I need to do another pull to update for the commit you just pushed.

2025-01-09 20:37 UTC, rpitingolo requested changes
@ekgutierrez1 added line item comments! Many of the comments from the city code also apply to the county as much of the code is duplicated.

2025-01-09 20:37 UTC, rpitingolo commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +global gitfolder "C:\Users\ekgut\OneDrive\Desktop\urban\Github\mobility-from-poverty"
Also from the checklist: "The program avoids hardcoding local file paths and instead uses global paths that will work regardless of where the program is being ran"

2025-01-09 20:37 UTC, rpitingolo commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +		foreach var in other {
Is there a reason this is coded as a loop with just 1 variable? Are other variables missing?

2025-01-09 20:37 UTC, rpitingolo commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +*Quality Checks
A lot of quality checks are difficult for me to interpret as someone without much topical knowledge of the data. For checks where a large number of summary stats are created it would be helpful to know what to look for in those numbers. Alternatively using pass/fail checks would be a bit easier to interpret.

2025-01-09 20:37 UTC, rpitingolo commented on 02_housing/Homelessness_metrics_county_subgroup.do
> +	replace other = 1 if other==.
There are two lines of commented out code in the loop: 

[	*replace `var'="1" if `var'=="S"
	*destring `var', replace](url)

Is this temporary or permanent? If permanent please delete these lines. It doesn't look like this is commented out in the city code.

2025-01-09 20:37 UTC, rpitingolo commented on 02_housing/Homelessness_metrics_county_subgroup.do
> +*To reviewer: in 2019, state 17 and county 061 there is an instance where black enrollment is 0 but homeless count is 3.
If we think this is an issue caused by the underlying data then it should probably be switched to the most conservative (unreliable data) flag and documented somewhere

2025-01-13 17:38 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +global gitfolder "C:\Users\ekgut\OneDrive\Desktop\urban\Github\mobility-from-poverty"
This uses a global - the user will have to hardcode this upon download. There isn't a way around this unfortunately. That's just how globals work.

2025-01-29 16:47 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +*Set up globals and directories
The error it provides (that the folders already exist) does not prevent the rest of the code from running. If it is a new user, this code auto-creates the paths they need. Since it doesn't prevent the rest of the code from running but is necessary for the paths of the code, I'd prefer to leave as is (this is how all of my files currently run, but we can ask the higher ups).

2025-01-29 16:53 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +*merge two ccd datasets together
Yes, it's expected. I added a line and a comment to explain.

2025-01-29 16:58 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +		keep if datagroup==655
It refers to "homeless students enrolled" rather than 818 which refers to "young homeless children served." I've added comments to clarify.

2025-01-29 17:02 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +		foreach var in other {
Not necessarily. The "other" variable needed the same adjustments that the previous race categories needed, but couldn't be included in the above loop as it aggregates some of the other race categories. I'll add a comment to clarify.

2025-01-29 17:04 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +*denominator changed from total homeless back to total of each race
If the underlying data is missing, then the ratio should be missing.

2025-01-29 17:17 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
>  	replace homeless_quality = 3 if enrollment<30
No, the next set of code/loop takes care of the individual race categories. It total homeless student count is less than 30, regardless of the individual race counts, the quality should be 3. However, if the individual race categories homeless counts are less than 10, they should be replaced with NA, because they are smaller categories than aggregated counts.

2025-01-29 17:23 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +merge 1:1 year state city_name using "intermediate/cityfile.dta"
It is correct because we only care about matches 2 and 3. I added some comments in the dofiles to help clarify.

2025-01-29 17:41 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_county_subgroup.do
> +	replace other = 1 if other==.
Great catch, I have now deleted that commented out code.

2025-01-29 17:52 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_county_subgroup.do
> +*To reviewer: in 2019, state 17 and county 061 there is an instance where black enrollment is 0 but homeless count is 3.
It's already a flag = 3 (most unreliable),but based on the underlying data, I think it should actually be NA. Making this change now.

2025-01-29 18:05 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +*Quality Checks
Added assert commands where relevant and comments for other checks.

2025-01-29 18:06 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +** Import city crosswalk file to edit names of city crosswalk to match city location strings in CCD school district data
I added relevant comments to this and the county dofiles.

2025-02-17 21:12 UTC, rpitingolo commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +*Set up globals and directories
What I meant is that the error stops the code at the point of the error. My understanding is that the code should run straight through without stopping but it seems like it's not possible in this case. Running the code in two chunks (the housekeeping part and the rest) works fine.

2025-02-17 21:14 UTC, rpitingolo commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +*Due to changes in EdDataExpress website, 2022-23 data must be manually downloaded. Please follow the following steps.
I wrote this comment before Jan 20 but this makes me even more nervous now. If we haven't already can we download the data and back it up somewhere (box maybe?). Same goes for the .zip files that are downloaded in the code. Hopefully the backups are never needed but better to have than the other way around.

2025-02-17 21:18 UTC, rpitingolo commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +*Due to changes in EdDataExpress website, 2022-23 data must be manually downloaded. Please follow the following steps.
FWIW I was still able to download the data using the instructions in the code comment today (Feb 17).

2025-02-17 21:22 UTC, rpitingolo commented on 02_housing/Homelessness_metrics_county_subgroup.do
> +	replace other = 1 if other==.
Great, thanks.

2025-02-27 16:44 UTC, rpitingolo commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +		keep if datagroup==655
Thank you!

2025-02-27 21:04 UTC, ekgutierrez1 commented on 02_housing/Homelessness_metrics_city_subgroup.do
> +*Due to changes in EdDataExpress website, 2022-23 data must be manually downloaded. Please follow the following steps.
both zip files and the manually downloaded data have been added to the box folder --> Metric_2025_round->Homeless_Students

2025-02-27 21:19 UTC, rpitingolo approved these changes
@ekgutierrez1 thanks!

2025-03-17 17:00 UTC, merged