Iss415
UI-Research/mobility-from-poverty pull request #438
Opened 2024-12-17 21:44 UTC by malcalakovalski

2025-01-06 15:08 UTC, wcurrangroome requested changes
Manu--this looks great overall. In particular, I really appreciate the clarity of the introduction to the metric at the top.

I left some minor comments throughout. A few overarching thoughts:

- I haven't really reviewed the county-level file yet. I imagine many of the city-level comments apply there as well. If you have the bandwidth and interest, and if it seems plausible, I'd love to see the city- and county-level code files consolidated into a single .qmd, with conditional logic treating the differences between the two. If that's not a priority, I'll plan to review the county-level code once the city-level code is essentially finalized.
- Querying the data from the API is a pain (can only imagine this has been a 10x headache for you). One issue I've run into is that the query works for some years, but for other years it fails. This doesn't error out, which is fine, but the result is that a subsequent check throws an error because I've got data for, e.g., 2015:2022, but not for 2014. Can you write results to disk year-by-year, and then only query years for which there aren't already local data? This might be the top priority in my mind at this point.
- Generally, I left a decent number of comments about stylistic things, which you should feel free to take or ignore as you see fit--they're obviously just my preference, and as far as I can tell with a subset of all the years' data, everything runs well at first blush, so they're definitely not critical changes.

2025-01-06 15:08 UTC, wcurrangroome commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +fetch_cbp_data <- function(year, naics_codes_to_keep) {
Building on this: I haven't been able to get all the years' data to download successfully. On different runs, I've gotten errors on at least one, and often multiple, years' worth of data. The code executes fully, but the resulting dataset fails one of the checks below. As-is, this requires re-running the entire query, i.e., for all data years, which is time-intensive. Could you modify this to download each year's data into a single file? Then add a check, year by year, for whether the data has already been downloaded? And then, once all years have been downloaded, read them in and combine them into a single longitudinal dataset?

2025-01-06 17:07 UTC, wcurrangroome commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +
Sorry, had missed your earlier comment about this very issue, @malcalakovalski! Tagging @cdsolari for her input here. I think we should use the CBP population data and produce 2014 estimates. If so, perhaps we want to note at the top that we use a different population source for this year as compared to the others. (Though--why do we not have population data for 2014 if we're producing estimates across many metrics for 2014?)

2025-02-18 15:44 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_county.qmd
> +  write_csv(here("06_neighborhoods/social-capital/data/social_associations_all_county.csv"))
I'm not sure I'm following! How should the file path be re written?

2025-02-18 15:47 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +years <- 2014
Yes, it was just for testing so I'll clean it up in my next round

2025-02-18 19:24 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
>  merged_sa_zip_city <-
Renamed!

2025-02-18 19:38 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +source(here("functions/testing/evaluate_final_data.R"))
done!

2025-02-19 16:44 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +**Check:** Are there exactly 9 missing values in the `new_est_zip` variable?
Yes, you are totally correct

2025-02-19 16:45 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +
I updated the code to use the 2014 population data added in the `version2025` branch

2025-02-25 03:16 UTC, wcurrangroome commented on 06_neighborhoods/social-capital/social_associations_county.qmd
> +  write_csv(here("06_neighborhoods/social-capital/data/social_associations_all_county.csv"))
Truly no idea what I was thinking at the time--ignore this!

2025-02-25 03:20 UTC, wcurrangroome commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +**Check:** Do 9,644 and 9,669 of these ZCTAs fall fully into a Census Place?
Bumping this. I assume this check is just to ensure consistency, i.e., if someone gets a different number here, something about the workflow has changed/gone wrong. If that's the case, add a quick clarifying note (and/or perhaps omit this check). Else--why do these numbers have significance / are worthwhile to assert via tests?

2025-02-25 03:25 UTC, wcurrangroome commented on 06_neighborhoods/social-capital/social_associations_city.qmd
>  of ZCTAs falling in each Place (duplicates)
Bumping this--from what I can see, these aren't duplicates.

2025-02-25 15:06 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +  message("Test failed: Missing years - ", paste(missing_years, collapse = ", "))
Yes you are so right. I just changed it!

2025-02-25 15:14 UTC, wcurrangroome requested changes
All looks great, Manu. I left two (I think) of my original comments that I bumped--let me know if you disagree with my suggestions, otherwise could you address those? (I believe both are about text clarity, not code--I don't see any errors). 

Only other thing I'm curious about: it looks like there's a precipitous decline in population-standardized association counts from 2016 to 2017 in both the place and county data. Do you know why that is? If possible, it'd be great to include a note about that somewhere in the code (preferably an explanation, else just a flag that we're aware of the change).

Once done, this looks good to go by me!

2025-02-25 15:39 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
>  ## Merge with the 2020 ZCTA -\> 2021 Census Place crosswalk
I'm not familiar with the differences between 2020 vintage places and the 2021 ones. Are you aware of any difference that would be good to at least flag here? Good point on describing _why_ this needs a crosswalk. I'll add that.

2025-02-25 15:57 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
> +fetch_cbp_data <- function(year, naics_codes_to_keep) {
I added a clarification at the top!

2025-02-25 16:02 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
>  of ZCTAs falling in each Place (duplicates)
Yes, you are correct! I removed this paranthetical

2025-02-25 16:11 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
>  5.  check against official Census Place file & limit to population cutoff Places
Yes you are correct, I ommitted reference to official going forward

2025-02-25 16:18 UTC, malcalakovalski commented
Hi @wcurrangroome, I believe I addressed all your edits in the last few commits from today. Let me know if I missed anything or if this is good to merge. Thank you!

2025-02-25 16:19 UTC, malcalakovalski commented on 06_neighborhoods/social-capital/social_associations_city.qmd
>  2.  import and clean the data file (collapse to unique ZIPs)
You are right, we are working with ZCTA's. I changed all the object names to refer to ZCTA's instead of ZIP

2025-02-25 18:24 UTC, wcurrangroome approved these changes
Good to go!

2025-03-17 17:08 UTC, merged