Iss400
UI-Research/mobility-from-poverty pull request #439
Opened 2024-12-20 17:54 UTC by ekgutierrez1

1) #400 

2) A description of the content in this pull request.  
- What was changed? City files (both all and subgroup) now have 2014-2018 data. 
- What should the reviewer be focusing on? I added some new quality checks. 
- Is there a logical order to review the files in? No

3) Detail on any issues or flags that the metric reviewer/data-team should be aware of. 
2018-19 is the most recent year of SEDA data available, and the crosswalk availability only goes back to 2014. The dofile creates previous years of data as part of the metric, so now that there are 2014/2015 crosswalk years, those were included here instead of in issue #401.

2025-01-06 17:56 UTC, ekgutierrez1 commented
A description of the content in this pull request.

What was changed? County files (both all and subgroup) now have 2014-2018 data.
What should the reviewer be focusing on? I added some new quality checks.
Is there a logical order to review the files in? No

Detail on any issues or flags that the metric reviewer/data-team should be aware of.
2018-19 is the most recent year of SEDA data available, and the crosswalk availability only goes back to 2014. The dofile creates previous years of data as part of the metric, so now that there are 2014/2015 crosswalk years, those were included here instead of in issue https://github.com/UI-Research/mobility-from-poverty/issues/401.

2025-01-09 17:58 UTC, ekgutierrez1 commented
county files 2014-2018 for all and subgroup have been updated using the new county crosswalk to include CT

2025-01-10 22:24 UTC, rpitingolo requested changes
@ekgutierrez1 I left more detailed comments in the line item review but I had some trouble running this code due to errors at various points. Hopefully once those are checked/fixed it's a smoother run.

2025-01-10 22:24 UTC, rpitingolo commented on 08_education/programs/SEDA_metrics_race_city.do
> +	merge m:1 city_name state year using "intermediate/cityfile.dta"
In the county code you are only merging by `year` so I wonder if that should be the case here too?

2025-01-13 17:34 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_county.do
>  cap n mkdir "intermediate"
When I run this code, the error doesn't stop the rest of the dofile from running. It just flags that it couldn't me made (because it already exists). When you run it top to bottom, does it stop the rest of the code from running?

2025-01-13 17:35 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_county.do
> +cap n copy "https://stacks.stanford.edu/file/druid:cs829jn7849/seda_county_long_gcs_5.0.dta" "raw/seda_county_long_gcs_5.0.dta"
That is strange, I haven't had issues in the past. Could you try again and see if it was just that day that the website was having trouble?

2025-01-29 16:40 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_county.do
> +cap n copy "https://stacks.stanford.edu/file/druid:cs829jn7849/seda_county_long_gcs_5.0.dta" "raw/seda_county_long_gcs_5.0.dta"
I just reran it and it pulled in the data immediately.

2025-01-29 19:16 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_city.do
> +	merge m:1 city_name state year using "intermediate/cityfile.dta"
I'm not sure the reason it's not running for you. I just ran it and didn't have any problems?

2025-01-29 19:18 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_city.do
> +	merge m:1 city_name state year using "intermediate/cityfile.dta"
This merge is to match the SEDA data to the city/place crosswalk that we report the metric for.

2025-01-29 19:19 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_city.do
> +	*brow state city_name _merge year if _merge!=3  // _merge=2 means its in city but not seda
Uncommented and left it as a data quality check for the future.

2025-01-29 19:20 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_city.do
> +	gen final_files = 1 if _merge!=1
Yes this relies on the _merge from the city crosswalk in order to run.

2025-01-29 19:23 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_county.do
> +	** NOTE: If the following doesn't work, download data in manually from SEDA website: https://edopportunity.org/get-the-data/seda-archive-downloads/ **
Correct - it is now fixed.

2025-01-29 19:28 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_city.do
> +	*figure out which of the SEDA observations do exist in other years & fill in
Comments added.

2025-01-29 20:15 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_county.do
> +	** NOTE: This loop takes a about 12:46 minutes to run.
Apologies, that was meant to communicate 12+ hours. Higher ups said they were going to try to find a work around to make it faster, but tbd when that will happen.

2025-01-29 20:40 UTC, ekgutierrez1 commented on 08_education/programs/SEDA_metrics_race_county.do
> +		reg gcs_mn_`subgroup' c.grade#county i.county if cohort==`cohort' [aw=tot_asmt_`subgroup']
I added comments to the dofile that were stated in the original readme. E Blom originally wrote that regression and described it in the readme. I'll add it to both the county and city dofiles.

2025-02-19 20:37 UTC, rpitingolo commented on 08_education/programs/SEDA_metrics_race_county.do
>  cap n mkdir "intermediate"
Since we resolved this on the other reviews I am going to mark this one as resolved too.

2025-02-19 20:37 UTC, rpitingolo commented on 08_education/programs/SEDA_metrics_race_county.do
> +cap n copy "https://stacks.stanford.edu/file/druid:cs829jn7849/seda_county_long_gcs_5.0.dta" "raw/seda_county_long_gcs_5.0.dta"
The issue must have been the computer I used. I re-tried it on a different computer and it finished in about 5 minutes.

2025-02-19 21:07 UTC, rpitingolo commented on 08_education/programs/SEDA_metrics_race_city.do
> +	merge m:1 city_name state year using "intermediate/cityfile.dta"
Was able to get the merge to run this time. Not sure what happened before.

2025-02-19 21:08 UTC, rpitingolo commented on 08_education/programs/SEDA_metrics_race_city.do
> +	*figure out which of the SEDA observations do exist in other years & fill in
Excellent. Thank you!

2025-02-19 21:18 UTC, rpitingolo commented on 08_education/programs/SEDA_metrics_race_city.do
> +	gen final_files = 1 if _merge!=1
OK I  think I've got it working now.

2025-02-27 20:27 UTC, rpitingolo approved these changes
@ekgutierrez1 thanks!

2025-03-26 19:50 UTC, merged